### ISSUE TITLE
Add an API to filter repositories from Github

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Backend#1]
Create an API to filter repositories from Github via github API.

**Comment by mbcse** [comment]
Doing this!

**Comment by irshadjsr21** [comment]
Sure, go ahead.

**Comment by irshadjsr21** [comment]
@mbcse What's the update on this?

**Comment by ManthanKeim** [comment]
I would like to work on this.

**Comment by raina02** [comment]
Hi Irshad
I would like to work on this!

**Comment by raina02** [comment]
Can you please further explain the process of the issue ?
