### ISSUE TITLE
create a POST /v1/discussion/:discussionId route to report a discussion

### ISSUE THREAD

**Issue by Dishebh** [OpenSouceCode/Backend#115]
create a POST `/v1/discussion/:discussionId` route that accepts `reason`, `userId` and `discussionId` in the request body & sends the data related to the `ReportDiscussion` created back in the response.

**Comment by priyanshupardhi** [comment]
Hey @Dishebh ,  by adding a form I can do this

**Comment by Dishebh** [comment]
@priyanshupardhi, sure, give it a try :). Take help from other already implemented routes.
