### ISSUE TITLE
Integrate mongodb with mongoose

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Backend#14]
Add mongodb setup with mongoose orm.

**Comment by ishank-dev** [comment]
I would like to take it up

**Comment by Dishebh** [comment]
@ishank-dev are you working on it, currently?

**Comment by Dishebh** [comment]
@irshadjsr21 I would like to work on this. Can you please provide a bit more detail regarding the issue, and what needs to be done?
