### ISSUE TITLE
Setup github oAuth login/signup

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Backend#16]
## Description

Setup a route for GitHub oAuth `/auth`. This will be a post route which will take in an access token of the GitHub user. 

This route will then fetch the user details from the GitHub API by sending the access token. It'll create a new user or login the existing user based on if the user already exists in the database.

The new user should be stored in a MongoDB collection named `users` with all the basic details from GitHub and the access token.

After login/signup this route should return a JWT for authentication.

**Comment by Dishebh** [comment]
@irshadjsr21 I would like to take this up
