### ISSUE TITLE
Create an authentication middleware

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Backend#17]
## Description

Create a middleware that checks the Authorization header for the JWT and validates it. If the JWT is invalid or expired, return a 401 response and if it is valid, call the next middleware.

**Comment by Dishebh** [comment]
@irshadjsr21 I would like to work on this.

**Comment by irshadjsr21** [comment]
Sure

**Comment by aryasoni98** [comment]
Yes, sure @Dishebh
