### ISSUE TITLE
Create a User model using mongoose schema

### ISSUE THREAD

**Issue by Dishebh** [OpenSouceCode/Backend#19]
Create a new `User` model with the collection having `keys` as - `name`, `email`, `username`, `password`, `profileAvatar`, `date` and `oAuth`.

**Comment by irshadjsr21** [comment]
Since we're using oAuth, there will be no password. Also there should be a field to store access token for the user. 

Also, what's the date and oAuth fields are for? There are already timestamps by mongoose.

**Comment by Dishebh** [comment]
`oAuth` to take in an object: 
`oAuth: {
   github: {
      profileUrl: { type: String, default: null },
      accessToken: { type: String, default: null }
}`

and `date` to store the `Date` when the `User` is registered.
