### ISSUE TITLE
create a route to list all the repositories starred by an authenticated user

### ISSUE THREAD

**Issue by Dishebh** [OpenSouceCode/Backend#39]
#### Description
create a GET route: `/user/starred` that lists all the repositories starred by an authenticated user. Check out the [Github rest API v3 docs](https://developer.github.com/v3/activity/starring/#list-repositories-starred-by-the-authenticated-user) for reference.

**Comment by Vaibhav-Ganatra** [comment]
Hello @Dishebh  @irshadjsr21 , I would like to work on this issue

**Comment by Souptik2001** [comment]
Hello @Vaibhav-Ganatra actually I am already about half-way done through this issue but forgot to mention it here. So, it would be great if you work on another issue. Sorry, for the inconvenience.

**Comment by irshadjsr21** [comment]
Please comment on the issues first before working on it.

**Comment by Souptik2001** [comment]
For sure from next time👍
